site_name: Instant Invoice Generator
theme:
  name: material

nav:
  - Accueil: index.md
  - Projects:
      - Backend:
          - Overview: projects/backend/index.md
          - Auth:
              - Authentication: projects/backend/auth.md
          - Architecture: projects/backend/architecture.md
          - ğŸ“¡ API:
              - Endpoints: projects/backend/api.md
              - Exemples d'appels: projects/backend/api-examples.md
          - ğŸ—ƒï¸ ModÃ¨les de donnÃ©es: projects/backend/models.md
          - ğŸ› ï¸ Utilisation:
              - Configuration: projects/backend/config.md
              - Interface CLI: projects/backend/cli.md
          - ğŸ§­ Planification:
              - Roadmap: projects/backend/roadmap.md
              - Journal des changements: projects/backend/changelog.md
plugins:
  - search
  - macros
